server:
  tomcat:
    threads:
      max: 800                    # 2배 증가: 더 많은 동시 요청 처리
      min-spare: 100             # 더 많은 대기 스레드 유지
    max-connections: 20000       # 2배 증가: 더 많은 TCP 연결 허용
    accept-count: 1000          # 2배 증가: 더 큰 대기열
    connection-timeout: 3000    # 더 빠른 타임아웃으로 실패 빠르게 감지
    keep-alive-timeout: 10000   # Keep-Alive 시간 감소로 리소스 빠른 해제

  # 추가 서버 설정
  compression:
    enabled: true               # 응답 압축 활성화
    min-response-size: 1024     # 최소 압축 크기
  max-http-request-header-size: 40KB # HTTP 헤더 크기 제한

# 추가적인 Spring 설정
spring:
  mvc:
    async:
      request-timeout: 10000    # 비동기 요청 타임아웃 감소
  datasource:
    hikari:
      maximum-pool-size: 50     # DB 커넥션 풀 크기 증가
      minimum-idle: 20
      connection-timeout: 3000  # DB 연결 타임아웃 감소